version: '3.8'

services:
  # خدمة قاعدة البيانات
  db:
    image: mysql:8.0
    container_name: salesapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - salesapp-network

  # خدمة واجهة برمجة التطبيقات (Backend)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: salesapp-backend
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACKEND_PORT}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - salesapp-network

  # خدمة واجهة المستخدم (Frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: salesapp-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - salesapp-network

  # أداة إدارة قاعدة البيانات
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: salesapp-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    networks:
      - salesapp-network

networks:
  salesapp-network:
    driver: bridge

volumes:
  db_data: